### ISSUE TITLE
Try using regression models to predict transposition insertion depending on the genomic length and position

### ISSUE THREAD

**Issue by leilaicruz** [Gregory94/LaanLab-SATAY-DataAnalysis#12]
It will be nice to apply statistical inference to a our large dataset to try to make meaningful predictions from the data. 
One example is to predict for example the continous variable of the number of transposon insertions per ORF given the length and the position of it.  For this what is recommended is to use Regression models. Whether we need linear or non linear models , we have to "discover it" by looking at the relationships between the variables . 
For inspiration , and examples you can look in this folder [LINK](https://github.com/Gregory94/LaanLab-SATAY-DataAnalysis/tree/dev_Leila/example-using-regression-to-predict-transposition) where I have some examples notebooks to try things out

**Comment by Wteunisse** [comment]
I don't think I understand this completely, why would you want to predict the number of transposons and what would you base your prediction on? Is this about what we discussed with the Poisson distribution?

**Comment by leilaicruz** [comment]
This was an idea to predict SATAY outcome if possible for new strains, without actually measuring them. However , the experimental outcome of this technique depends on experimental factors like : incubation times, incubation media, number of cells to reseed, etc.  

However maybe still interesting as outlook is to simulate the SATAY experiment in a computer to play with all those factors as parameters of a model.  And then we can see the effects of changing different parameters on the transposition efficiency. 

I will close this issue since it does not have a clear follow up .
