### ISSUE TITLE
Writing a workflow for SATAY analysis using the command line.

### ISSUE THREAD

**Issue by leilaicruz** [Gregory94/LaanLab-SATAY-DataAnalysis#4]

**Comment by Gregory94** [comment]
A step-by-step explanation including commands for the bash is added to [the satay_analysis_notes file](https://github.com/Gregory94/LaanLab-SATAY-DataAnalysis/blob/dev_Gregory/docs/satay_analysis_notes.md). For each step it tells how to use the software, what settings to be set and a suggestion for organizing the data.
