### ISSUE TITLE
Create visual overview of reads per gene.

### ISSUE THREAD

**Issue by Gregory94** [Gregory94/LaanLab-SATAY-DataAnalysis#6]
Create several visualizations for creating an overview of the transposon insertion location and the number of reads.
Current progress is primarily in the [gene_reads.py file](https://github.com/Gregory94/LaanLab-SATAY-DataAnalysis/blob/dev_Gregory/Python_scripts/gene_reads.ipynb) which includes:
- A bar plot that counts the number of reads per region in the gene.
- A graph where the distribution of the distance between subsequent insertions is shown and compared with the distribution for the entire chromosome.

![Read_ProfilePlot_bem1](https://user-images.githubusercontent.com/29129193/82899212-e240ec00-9f5a-11ea-8e1a-93b494a69f1b.png)

**Comment by leilaicruz** [comment]
Can you put here also the visualizations you got? we can use this issue to discuss what you found :)
